### PR TITLE
Add CNAME

### PR DESCRIPTION
**Pull request by sebohe**

### CODE REVIEW

**Comment by sebohe** [comment]
Remove it from where? CNAME was never in `master`. You did add it to `gh-pages` but like you said that always gets overwritten when anyone does a `mkdocs gh-deploy`.

I didn't remove CNAME from the `gh-pages` branch. `mkdocs` did. All I did in: https://github.com/hashcloak/Meson/commits/gh-pages was do a `mkdocs gh-deploy` from my local `master` branch, which doesn't have CNAME so it got removed from the `gh-pages` branch.

This PR adds CNAME to `master` and moves `dcs/docs/*` to `docs`

**Comment by sebohe** [comment]
We should try to write protect gh-pages and use github actions to do the deployment to the gh-pages branch.

**Comment by Mikerah** [comment]
I see. There's no need to put it in master as long as the CNAME is in the correct directory in the gh-pages branch. That's where the site is served from not master, per se.

**Comment by sebohe** [comment]
the whole gh-pages branch gets nuked from the build output of mkdocs. Essentially what `mkdocs gh-deploy` does its copy the contents of `site/*` (the build output) into the root of the `gh-pages`.

So anything that is not inside of the source docs folder gets rewritten. This means that CNAME has to exist somewhere outside of the gh-pages branch.

This is what I did with the burner wallet: https://github.com/althea-net/efectivo-web/tree/master/public

**Comment by sebohe** [comment]
Closing in favor of: https://github.com/hashcloak/Meson/issues/101

**Pull request closed without merging**
